[package]
name = "generator-rs"
version = "0.1.0"
authors = ["Huy <kingbazoka@gmail.com>"]

[dependencies]
comrak = "0.2"
regex = "1.0.0"
rss = "1.5.0"
time = "0.1.40"
dotenv = "0.11.0"
rouille = "2.1.0"
chrono = "0.4.6"